### ISSUE TITLE
everythings are fine but it doesnt work

### ISSUE THREAD

**Issue by Valdes11** [AliKhadivi/tariq#13]
everythings are fine but it doesnt work

**Comment by AliKhadivi** [comment]
Check port 53 is available. Ubuntu by default run a DNS server.
If you are using Ubuntu, disable `systemd-resolved`

**Comment by AliKhadivi** [comment]
Unfortunately, I don't have time.

**Comment by AliKhadivi** [comment]
You can use free Shecan: https://shecan.ir
Or pay Shecan Pro: https://support.peygir.net/order?order=9
