### ISSUE TITLE
I have problems

### ISSUE THREAD

**Issue by Nicoozec** [AliKhadivi/tariq#67]
Hello, I have a problem, everything starts correctly but I get these errors.
Could you help me, thanks a lot.

![image](https://github.com/AliKhadivi/tariq/assets/82375879/44af9dcf-7800-4287-a460-b347b8f0740f)

**Comment by AliKhadivi** [comment]
Hello.  I think you haven't started Tariq service.  Before running the encryption service, you must first start the Tariq service.

### Start Tariq and enable it on boot

```bash
sudo tariq start
sudo tariq enable
```

### Check if it's running

```bash
sudo tariq status
```
